# Generated by Django 3.2.18 on 2023-04-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0002_auto_20230418_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
