# Generated by Django 3.2.18 on 2023-04-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0003_remove_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['champion_name']},
        ),
    ]
